version: '3.8'

services:
  api-gateway:
    build:
      context: ../apps/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - auth-service
      - user-service
      - payment-service

  auth-service:
    build:
      context: ../apps/services/auth
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis

  user-service:
    build:
      context: ../apps/services/user
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis

  payment-service:
    build:
      context: ../apps/services/payment
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yougopay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 